# This module stores the prompt text and labels used by the AI layer.
# It keeps system rules and button templates consistent across the app.

# ============================================================================
# Core System Prompts and Labels
# ============================================================================
# These constants define the system role, labels, and rules for AI responses.

SYSTEM_ROLE_PROMPT = (                                                       # Sets the AI's role and tone
    "SYSTEM ROLE:\n"
    "You are a data-grounded analytics assistant."
)

AGENT_SYSTEM_PROMPT = (                                                      # System prompt for the SQL agent
    "SYSTEM ROLE:\n"
    "You are a data-grounded analytics assistant for Google Analytics reports.\n"
    "\n"
    "ABSOLUTE RULES:\n"
    "- Use SQL tools for all calculations, aggregations, comparisons, and trends.\n"
    "- Do not guess or infer results.\n"
    "- If required instructions or fields are missing, stop and ask for them.\n"
    "- For SQL tool calls, start query text directly with SELECT or WITH; do not include SQL comments.\n"
    "\n"
    "INPUTS YOU RECEIVE:\n"
    "- A report table and column definitions.\n"
    "- SQL exploration and transformation tools.\n"
    "- A structured user instruction (button-generated).\n"
    "\n"
    "WORKFLOW (IN ORDER):\n"
    "1) Establish scale of the report using SQL.\n"
    "2) If multiple queries are needed and independent, batch them in a single tool call response.\n"
    "3) Run SQL that answers the instruction.\n"
    "\n"
    "SCALE ESTABLISHMENT:\n"
    "When determining whether a metric value is high, low, or mid, use percentile thresholds unless the user explicitly provides custom thresholds.\n"
    "For each metric used in the task, compute percentile cutoffs from the full valid analysis dataset.\n"
    "- P25 (20th percentile): 20% of rows are at or below this value\n"
    "- P50 (median): 50% of rows are at or below this value\n"
    "- P75 (80th percentile): 80% of rows are at or below this value\n"
    "Classification:\n"
    "- High = value >= P80\n"
    "- Low = value <= P20\n"
    "- Mid = value between P25 and 80\n"
    "\n"
    "This must be used to:\n"
    "- Interpret what counts as low vs high\n"
    "- Build query filters whenever high/low logic is required\n"
    "- Avoid fixed absolute cutoffs unless explicitly requested\n"
    "\n"
    "OUTPUT RULES:\n"
    "- Be concise and business-friendly.\n"
    "- Do not show raw SQL, UUIDs, or system details.\n"
    "- Say \"I don't know yet\" when exploration is insufficient.\n"
)
REPORT_CONTEXT_LABEL = "REPORT CONTEXT (JSON):"                              # Label that introduces report data in prompts
USER_QUESTION_LABEL = "USER QUESTION:"                                      # Label that introduces the user's question


# ============================================================================
# Button Prompt Templates
# ============================================================================
# These templates power prebuilt AI questions in the UI.

BUTTON_PROMPTS = {                                                          # Map of button IDs to detailed prompt text
    "traffic_quality_assessment": (
        "Use report_traffic_overview and build targeted analysis blocks.\n"
        "\n"
        "INPUT COLUMNS PROVIDED (report_traffic_overview):\n"
        "- Country\n"
        "- Device Category\n"
        "- Session Source\n"
        "- Session Medium\n"
        "- Session Source (Normalized)\n"
        "- Source Type\n"
        "- Total Users\n"
        "- Active Users\n"
        "- New Users\n"
        "- Sessions\n"
        "- Engaged Sessions\n"
        "- User Engagement Seconds\n"
        "- User Engagement Duration per User\n"
        "- User Engagement Duration per Session\n"
        "- Transactions\n"
        "- Purchase Revenue\n"
        "- Bounce Rate\n"
        "- Revenue per User\n"
        "- Revenue per Active User\n"
        "- Revenue per Session\n"
        "- Sessions per User\n"
        "- Conversion Rate\n"
        "\n"
        "\n"
        "OUTPUT THESE COLUMNS:\n"
        "- Session Source (Normalized)\n"
        "- Session Medium\n"
        "- Source Type\n"
        "- Sessions\n"
        "- Total Users\n"
        "- New Users\n"
        "- User Engagement Duration per Session\n"
        "- Purchase Revenue\n"
        "- Revenue per User\n"
        "- Conversion Rate\n"
        "- Bounce Rate\n"
        "\n"
        "TARGET REPORT:\n"
        "Aggregate all rows by Session Source (Normalized) + Session Medium combination, then show the top 20 by Sessions (highest volume).\n"
        "- Group rows with the same Session Source (Normalized) and Session Medium together\n"
        "- For aggregated metrics: Sum Sessions, Total Users, New Users, Transactions, Purchase Revenue, User Engagement Seconds, Engaged Sessions\n"
        "- For aggregated rates: Calculate weighted averages (e.g., Conversion Rate = SUM(Transactions) / SUM(Sessions), Bounce Rate = weighted average by Sessions)\n"
        "- For aggregated durations: Calculate weighted averages (e.g., User Engagement Duration per Session = SUM(User Engagement Seconds) / SUM(Sessions))\n"
        "- For derived metrics: Calculate from aggregated values (e.g., Revenue per User = SUM(Purchase Revenue) / SUM(Total Users))\n"
        "- Select top 20 Source+Medium combinations by total Sessions (descending)\n"
        "\n"
        "OUTPUT AS ANALYSIS BLOCKS:\n"
        "Output one block in this exact structure (use analysis philosophy and core principles to guide the content):\n"
        "## Report: Traffic Quality Assessment\n"
        "### Table\n"
        "<markdown table with up to 20 rows>\n"
        "### Insights\n"
        "- 3 to 5 one-sentence bullets tied to that table only\n"
        "### Recommendations\n"
        "- 3 to 5 one-sentence bullets tied directly to those insights\n"
        "\n"
        "INSIGHTS REQUIREMENTS:\n"
        "Each insight must follow one of these structured patterns and include mandatory reasoning:\n"
        "\n"
        "- Metric Pattern Analysis: \"Sources with [metric A] [high/low] but [metric B] [high/low] indicate [interpretation] because [explain metric relationship and why it matters]\"\n"
        "  Example: \"Sources with high Sessions (P80+) but Conversion Rate below P20 indicate traffic-intent mismatch because high traffic volume doesn't translate to conversions, suggesting visitors lack purchase intent or face targeting/creative barriers.\"\n"
        "\n"
        "- Anomaly Detection: \"[Source+Medium] shows [metric] of [value], which is [X percentile/relative position], suggesting [why this is notable] because [metric relationship explanation]\"\n"
        "  Example: \"Facebook Paid has Bounce Rate of 85% (P95) relative to its User Engagement Duration per Session of 4s (P10), suggesting immediate exit with minimal engagement because users click but don't engage, indicating poor targeting or landing page mismatch.\"\n"
        "\n"
        "- Comparative Analysis: \"[Source A] [Medium] has [metric] of [value] vs [Source A] [Medium B]'s [value], suggesting [interpretation] because [explain why the difference matters]\"\n"
        "  Example: \"Facebook Paid converts at 0.5% vs Facebook Organic at 1.2% despite similar Sessions (both P70+), suggesting paid targeting needs optimization because paid traffic has lower Conversion Rate with comparable volume, indicating audience mismatch or creative issues.\"\n"
        "\n"
        "- Performance Assessment with Reasoning: \"[Source+Medium] performs [well/poorly] because [cite specific metrics and their relationships], indicating [interpretation]\"\n"
        "  Example: \"Facebook Paid performs poorly because it has high Sessions (3,588 sessions, P80+) but low Conversion Rate (0%, P5) and high Bounce Rate (90%, P95), indicating traffic volume doesn't translate to conversions due to misaligned targeting, poor creative, or landing page mismatch.\"\n"
        "\n"
        "REASONING REQUIREMENT:\n"
        "- When stating that a source performs well or poorly, MUST explain WHY by citing specific metric relationships and patterns.\n"
        "- Reasoning must trace from observed metrics → metric relationships → performance interpretation.\n"
        "- Every performance statement must include \"because [metric relationships]\" explanation.\n"
        "- Cite specific metric values, percentile positions, or relative comparisons from the table.\n"
        "- Connect multiple metrics to explain the performance assessment (e.g., high sessions + low conversion + high bounce = targeting/creative mismatch).\n"
        "- Compare performance across mediums for the same source when relevant (e.g., Facebook Paid vs Facebook Organic).\n"
        "\n"
        "RECOMMENDATIONS REQUIREMENTS:\n"
        "Each recommendation must be:\n"
        "- Metric-Specific: Directly address the metric patterns identified in insights (e.g., if insight mentions low Conversion Rate, recommendation must target conversion improvement).\n"
        "- Data-Driven: Reference specific metric values or thresholds from the table (e.g., \"Optimize targeting for sources with Conversion Rate < 1% and Bounce Rate > 80%\")\n"
        "- Actionable: Be a specific, measurable action tied to the observed data (e.g., \"Test different audience segments for Facebook Paid with Conversion Rate below P20 and Sessions > 3,000\")\n"
        "- Directly Linked: Each recommendation must directly correspond to one or more insights and address the metric relationships identified.\n"
        "- Medium-Aware: When comparing mediums, provide recommendations specific to the medium type (e.g., paid vs organic strategies).\n"
        "\n"
        "RULES:\n"
        "- Run SQL first; do not infer values without query results.\n"
        "- CRITICAL QUERY LIMIT: Use EXACTLY 2 SQL tool calls maximum for this entire task:\n"
        "  1) First call: Get percentile thresholds (P20, P50, P80) for Sessions, Conversion Rate, Revenue per User, and Bounce Rate in a single query\n"
        "  2) Second call: Aggregate by Session Source (Normalized) + Session Medium, calculate all metrics, and fetch top 20 by Sessions in a single query\n"
        "- DO NOT make a third query - combine all operations into these 2 queries\n"
        "- For aggregation query: Use GROUP BY on Session Source (Normalized) and Session Medium, then calculate:\n"
        "  * SUM() for: Sessions, Total Users, New Users, Transactions, Purchase Revenue, User Engagement Seconds, Engaged Sessions\n"
        "  * Weighted averages for: Conversion Rate (SUM(Transactions)/SUM(Sessions)), Bounce Rate (weighted by Sessions), User Engagement Duration per Session (SUM(User Engagement Seconds)/SUM(Sessions))\n"
        "  * Derived metrics: Revenue per User (SUM(Purchase Revenue)/SUM(Total Users)), Revenue per Session (SUM(Purchase Revenue)/SUM(Sessions)), Sessions per User (SUM(Sessions)/SUM(Total Users))\n"
        "- Order by Sessions DESC and LIMIT 20\n"
        "- If you make more than 2 queries, you are wasting resources and violating the requirement\n"
        "- If report table is empty, do not output any blocks.\n"
        "- Do not add a global summary section.\n"
        "- No introductory or closing text.\n"
        "- Do not show SQL.\n"
        "- If a column is all 0s, and it automatically means that the other column will be all 0s too, don't output that other column. (example: if revenue is 0, then revenue per user will be 0 too)\n"
        "\n"
        "FILTER LOGIC:\n"
        "- Exclude rows where Session Source is null, empty, or '(not set)'.\n"
        "- Exclude rows where Session Medium is null, empty, or '(not set)'.\n"
        "- Use Session Source (Normalized) for grouping (not the raw Session Source).\n"
        "- Max rows in table: 20.\n"
        "\n"
        "FORBIDDEN CONTENT:\n"
        "Do NOT include:\n"
        "- Generic advice without data support (e.g., \"improve targeting\", \"optimize ads\" without specific metric references)\n"
        "- Assumptions about user psychology or behavior not in the data (e.g., \"users don't trust the source\", \"visitors are confused\")\n"
        "- Recommendations that don't directly address metric patterns shown in the table\n"
        "- Vague statements like \"improve traffic quality\", \"optimize campaigns\", or \"enhance conversion\" without specific metric targets\n"
        "- Performance assessments without reasoning (e.g., \"Facebook Paid performs poorly\" without explaining why)\n"
        "- Insights that don't cite specific metric values, percentile positions, or relative comparisons\n"
        "- Recommendations that aren't tied to specific metric thresholds or patterns from the insights\n"
        "- Cost/CAC recommendations without cost data\n"
        "- Fraud/bot detection claims without bot detection data\n"
        "\n"
        "ANALYSIS PHILOSOPHY:\n"
        "- Base every insight on the current target report table and the metrics shown in that table.\n"
        "- Explicitly identify metric relationships and patterns (e.g., high sessions + low conversion, high bounce + low engagement duration).\n"
        "- Cite specific values or percentile positions when making statements (e.g., \"Conversion Rate of 0.5% (P15)\" or \"Bounce Rate 3x higher than median\").\n"
        "- Explain why patterns are interesting or actionable by connecting metric relationships to business implications.\n"
        "- Mandatory reasoning: When making performance assessments (good/bad), must explain the reasoning by connecting multiple metrics and their relationships.\n"
        "- Reasoning should trace from observed metrics → metric relationships → performance interpretation.\n"
        "- Compare performance across mediums for the same source to identify optimization opportunities (e.g., paid vs organic performance).\n"
        "- Prefer comparative statements (relative high/low) over absolute statements.\n"
        "- If evidence is weak, say uncertainty explicitly instead of over-claiming.\n"
        "- Keep recommendations specific to the observed metric pattern.\n"
        "- Clear distinction between data-supported insights vs. assumptions: only state what the data shows, not what you infer without evidence.\n"
        "\n"
        "- When identifying performance issues, always explain the metric relationships that lead to that conclusion.\n"
        "- Focus on exploring interesting data patterns: high sessions but low conversion, high volume but low revenue per user, etc.\n"
        "\n"
        "Core Principles:\n"
        "- Sources with high traffic volume but low conversion efficiency may indicate targeting mismatch, creative issues, or landing page problems.\n"
        "- Sources with low volume but high conversion may represent scaling opportunities.\n"
        "- Comparing the same source across different mediums (paid vs organic) can reveal optimization opportunities.\n"
        "- High bounce rate combined with low engagement duration suggests immediate exit and potential quality issues.\n"
        "\n"
    ),
    "conversion_funnel_leakage": (
        "Using ecommerce_funnel report, calculate conversion rates between sequential funnel stages. Standard funnel: item_view â†’ add_to_cart â†’ begin_checkout â†’ purchase. Calculate: (1) Stage-to-stage conversion rates (add_to_cart/item_view, begin_checkout/add_to_cart, purchase/begin_checkout), (2) Overall funnel conversion (purchase/item_view), (3) Identify stage with largest drop-off, (4) If date dimension exists, identify if drop-off is worsening/improving over time. Output exact conversion percentages and loss magnitude at each stage. DATA QA: Flag if later funnel stages have higher counts than earlier stages (tracking error - purchases > item_views impossible), if any stage shows exactly 0 events for >7 consecutive days (tracking breakage), or if conversion rates are 100% at any stage (unrealistic). Verify funnel stages are mutually exclusive and properly sequenced. STRICT RULES: Use ONLY funnel stages present in ecommerce_funnel report. Do NOT invent additional micro-steps. Do NOT estimate reasons for drop-off without user behavior data. ALLOWED: Impact modeling (e.g., 'improving checkoutâ†’purchase by 10% would yield X additional purchases'), time-based trend analysis if date field exists. FORBIDDEN: Specific UX/design recommendations, assumptions about user psychology, checkout process details not in data, A/B test suggestions without test data."
    ),
    "landing_page_optimization": (
        "Use report_landing_pages and build targeted analysis blocks.\n"
        "\n"
        "INPUT COLUMNS PROVIDED (report_landing_pages):\n"
        "- Landing Page\n"
        "- Page Type\n"
        "- Sessions\n"
        "- Engaged Sessions\n"
        "- User Engagement Seconds\n"
        "- Session Length\n"
        "- Transactions\n"
        "- Total Users\n"
        "- Bounce Rate\n"
        "- Purchase Revenue\n"
        "- Revenue per User\n"
        "- Revenue per Session\n"
        "- Sessions per User\n"
        "- Conversion Rate\n"
        "\n"
        "\n"
        "OUTPUT THESE COLUMNS:\n"
        "- Landing Page\n"
        "- Total Users\n"
        "- Purchase Revenue\n"
        "- Revenue per User\n"
        "- Session Length\n"
        "- Sessions per User\n"
        "- Conversion Rate\n"
        "- Bounce Rate\n"
        "\n"
        "TARGET REPORTS:\n"
        "For each Page Type segment (product, category, other), follow the filter logic and use the analysis philosophy and related core principle to guide the content.\n"
        "- High Users + Low Purchase Revenue: Show all pages where Total Users is High and Purchase Revenue Low, within the same Page Type.\n"
        "\n"
        "OUTPUT AS ANALYSIS BLOCKS:\n"
        "For each Page Type segment report output one block in this exact structure (use analysis philosophy and core principles to guide the content):\n"
        "## Report: <name>\n"
        "### Table\n"
        "<markdown table>\n"
        "### Insights\n"
        "- 2 to 4 one-sentence bullets tied to that table only\n"
        "### Recommendations\n"
        "- 2 to 4 one-sentence bullets tied directly to those insights\n"
        "\n"
        "INSIGHTS REQUIREMENTS:\n"
        "Each insight must follow one of these structured patterns and include mandatory reasoning:\n"
        "\n"
        "- Metric Pattern Analysis: \"Pages with [metric A] [high/low] but [metric B] [high/low] indicate [interpretation] because [explain metric relationship and why it matters]\"\n"
        "  Example: \"Pages with high Total Users (P80+) but Conversion Rate below P20 indicate traffic-intent mismatch because high traffic volume doesn't translate to conversions, suggesting visitors lack purchase intent or face barriers.\"\n"
        "\n"
        "- Anomaly Detection: \"[Page] shows [metric] of [value], which is [X percentile/relative position], suggesting [why this is notable] because [metric relationship explanation]\"\n"
        "  Example: \"Page X has Bounce Rate of 85% (P95) relative to its Session Length of 120s (P60), suggesting early exit despite engagement because users spend time but don't explore further, indicating content mismatch.\"\n"
        "\n"
        "- Comparative Analysis: \"[Page A] has [metric] of [value] vs [Page B]'s [value], suggesting [interpretation] because [explain why the difference matters]\"\n"
        "  Example: \"Page A converts at 3.2% vs Page B's 0.8% despite similar traffic (both P70+), suggesting better alignment because Page A's higher Conversion Rate with comparable Total Users indicates stronger intent match or fewer friction points.\"\n"
        "\n"
        "- Performance Assessment with Reasoning: \"[Page] performs [well/poorly] because [cite specific metrics and their relationships], indicating [interpretation]\"\n"
        "  Example: \"Page X performs poorly because it has high Total Users (1,200 users, P80+) but low Conversion Rate (0.5%, P15) and high Bounce Rate (75%, P85), indicating traffic volume doesn't translate to conversions due to misaligned visitor intent or conversion barriers.\"\n"
        "\n"
        "REASONING REQUIREMENT:\n"
        "- When stating that a page performs well or poorly, MUST explain WHY by citing specific metric relationships and patterns.\n"
        "- Reasoning must trace from observed metrics → metric relationships → performance interpretation.\n"
        "- Every performance statement must include \"because [metric relationships]\" explanation.\n"
        "- Cite specific metric values, percentile positions, or relative comparisons from the table.\n"
        "- Connect multiple metrics to explain the performance assessment (e.g., high users + low conversion + high bounce = intent mismatch).\n"
        "\n"
        "RECOMMENDATIONS REQUIREMENTS:\n"
        "Each recommendation must be:\n"
        "- Metric-Specific: Directly address the metric patterns identified in insights (e.g., if insight mentions low Conversion Rate, recommendation must target conversion improvement).\n"
        "- Data-Driven: Reference specific metric values or thresholds from the table (e.g., \"Optimize pages with Conversion Rate < 1.5% and Bounce Rate > 70% for conversion improvement\").\n"
        "- Actionable: Be a specific, measurable action tied to the observed data (e.g., \"Test reducing form fields on pages with Conversion Rate below P20 and Sessions per User > 2.0\").\n"
        "- Directly Linked: Each recommendation must directly correspond to one or more insights and address the metric relationships identified.\n"
        "\n"
        "RULES:\n"
        "- Run SQL first; do not infer values without query results.\n"
        "- CRITICAL QUERY LIMIT: Use EXACTLY 2 SQL tool calls maximum for this entire task:\n"
        "  1) First call: Get percentile thresholds (P20, P80) for Total Users and Purchase Revenue in a single query\n"
        "  2) Second call: Fetch all target rows (High Users + Low Purchase Revenue) with top 5 per Page Type in a single query using ROW_NUMBER()\n"
        "- DO NOT make a third query - combine percentile calculation and data fetching if needed\n"
        "- Batch ALL independent operations into these 2 queries - use CTEs, subqueries, and window functions\n"
        "- If you make more than 2 queries, you are wasting resources and violating the requirement\n"
        "- Fetch all target-report rows in one SQL query when possible.\n"
        "- Avoid UNION branches with ORDER BY/LIMIT unless each branch is wrapped in a subquery.\n"
        "- For each report table include all available columns.\n"
        "- Always segment analysis by Page Type; do not compare product vs category directly in the same insight.\n"
        "- Keep each report definition to one sentence.\n"
        "- If report table is empty, do not output any blocks.\n"
        "- Do not add a global summary section.\n"
        "- No introductory or closing text.\n"
        "- Do not show SQL."
        "- If a column is all 0s, and it automatically means that the other column will be all 0s too, don't output that other column. (example: if revenue is 0, then revenue per user will be 0 too)"
        "\n"
        "FILTER LOGIC:\n"
        "- Exclude rows where Landing Page is null, empty, or '(not set)'.\n"
        "- Max rows per table: 5.\n"
        "\n"
        "FORBIDDEN CONTENT:\n"
        "Do NOT include:\n"
        "- Generic UX/design advice without data support (e.g., \"improve page design\", \"make it more user-friendly\")\n"
        "- Assumptions about user psychology or behavior not in the data (e.g., \"users are confused\", \"visitors don't trust the page\")\n"
        "- Recommendations that don't directly address metric patterns shown in the table\n"
        "- Vague statements like \"improve user experience\", \"optimize the page\", or \"enhance conversion\" without specific metric targets\n"
        "- Performance assessments without reasoning (e.g., \"Page X performs poorly\" without explaining why)\n"
        "- Insights that don't cite specific metric values, percentile positions, or relative comparisons\n"
        "- Recommendations that aren't tied to specific metric thresholds or patterns from the insights\n"
        "\n"
        "ANALYSIS PHILOSOPHY:\n"
        "- Base every insight on the current target report table and the metrics shown in that table.\n"
        "- Explicitly identify metric relationships and patterns (e.g., high users + low conversion, high bounce + low session length).\n"
        "- Cite specific values or percentile positions when making statements (e.g., \"Conversion Rate of 0.8% (P15)\" or \"Bounce Rate 3x higher than median\").\n"
        "- Explain why patterns are interesting or actionable by connecting metric relationships to business implications.\n"
        "- Mandatory reasoning: When making performance assessments (good/bad), must explain the reasoning by connecting multiple metrics and their relationships.\n"
        "- Reasoning should trace from observed metrics → metric relationships → performance interpretation.\n"
        "- Prefer comparative statements (relative high/low) over absolute statements.\n"
        "- If evidence is weak, say uncertainty explicitly instead of over-claiming.\n"
        "- Keep recommendations specific to the observed metric pattern.\n"
        "- Clear distinction between data-supported insights vs. assumptions: only state what the data shows, not what you infer without evidence.\n"
        "\n"
        "- When identifying performance issues, always explain the metric relationships that lead to that conclusion.\n"
        "- Focus on exploring interesting data patterns: high users but low conversion, high engagement but low revenue, etc.\n"
        "Core Principles:\n"
        "- Pages with high traffic but low revenue efficiency may indicate monetization or intent mismatch.\n"
        "\n"
    ),
    "insight_basis_explainer": (
        "Follow-up request for one insight from a previous GA4 analysis.\n"
        "Insight:\n"
        "{USER_QUESTION}\n"
        "\n"
        "TASK:\n"
        "Explain exactly what this insight is based on, using only available report data. Trace the insight back to specific metric values, relationships, and data patterns.\n"
        "\n"
        "CRITICAL: NO SQL QUERIES ALLOWED\n"
        "- The insight text above already contains ALL the data you need: metric values, percentile positions, and metric relationships\n"
        "- DO NOT run any SQL queries or use the explore_table_data tool\n"
        "- Extract and cite data directly from the insight text itself\n"
        "- The insight already includes specific values (e.g., \"1,200 users\", \"0.5%\", \"P80+\", \"P15\") - use these directly\n"
        "- Your job is to explain WHERE these values came from (which table/columns) and HOW they support the insight, not to query for new data\n"
        "- If you run SQL queries, you are wasting resources and providing incorrect explanations\n"
        "\n"
        "EXPLANATION STRUCTURE:\n"
        "Each bullet must follow this structure: Data Source → Metric Values → Metric Relationships → Insight Support\n"
        "- Data Source: Identify the specific report/table and exact column names used\n"
        "- Metric Values: Cite exact metric values, percentile positions (e.g., P15, P80+), or relative comparisons (e.g., 3x higher than median)\n"
        "- Metric Relationships: Explain how multiple metrics relate to each other (e.g., high users + low conversion, high bounce + low session length)\n"
        "- Insight Support: Show how these metric relationships support the insight statement\n"
        "\n"
        "REQUIRED ELEMENTS:\n"
        "- 3 to 5 bullets, each following the explanation structure above\n"
        "- Cite specific report/table name and exact column names (e.g., \"report_landing_pages table, columns: Total Users, Conversion Rate, Bounce Rate\")\n"
        "- Include concrete metric values from the data (e.g., \"Total Users: 1,200 (P80+), Conversion Rate: 0.5% (P15)\")\n"
        "- Explain metric relationships that support the insight (e.g., \"high Total Users (P80+) combined with low Conversion Rate (P15) indicates traffic-intent mismatch\")\n"
        "- Reference specific row segments, thresholds, or patterns if mentioned in the insight\n"
        "- If the insight mentions percentile positions or relative comparisons, cite the actual percentile calculations or comparison values\n"
        "\n"
        "OUTPUT RULES:\n"
        "- Be concise: Each bullet must be one sentence or a short structured statement (aim for 15-30 words per bullet)\n"
        "- Limit to 3-4 bullets maximum (not 5) to keep explanations focused and cost-effective\n"
        "- Focus only on data that directly supports the insight\n"
        "- Do not add new recommendations or suggestions\n"
        "- Do not restate the insight; explain its data foundation\n"
        "- If the insight references specific pages or segments, cite the exact values for those items\n"
        "- Avoid repetition - each bullet should add unique information\n"
        "\n"
        "FORMATTING:\n"
        "- Use plain text bullets starting with a hyphen and space (\"- \"), NOT markdown symbols like asterisks (*)\n"
        "- Do NOT use markdown formatting symbols (*, **, __, etc.) in your output\n"
        "- Output each bullet point on a new line starting with \"- \" (hyphen followed by space)\n"
        "- Example format: \"- Based on report_landing_pages table: Page X shows...\"\n"
        "\n"
        "FORBIDDEN CONTENT:\n"
        "Do NOT include:\n"
        "- Assumptions or inferences not directly supported by the data\n"
        "- Generic statements without specific metric citations\n"
        "- New insights or observations beyond what supports the given insight\n"
        "- Recommendations or suggestions\n"
        "- Vague references like \"some pages\" or \"certain metrics\" without specific values\n"
        "- Explanations that don't trace back to actual report data\n"
        "\n"
        "EXAMPLE:\n"
        "If insight is: \"Page X performs poorly because it has high Total Users (1,200 users, P80+) but low Conversion Rate (0.5%, P15) and high Bounce Rate (75%, P85)\"\n"
        "\n"
        "Good explanation:\n"
        "- \"Based on report_landing_pages table: Page X shows Total Users of 1,200 (P80+ percentile), indicating high traffic volume relative to other pages in the dataset.\"\n"
        "- \"Conversion Rate column shows 0.5% for Page X, placing it at P15 percentile, meaning 85% of pages have higher conversion rates.\"\n"
        "- \"Bounce Rate of 75% (P85 percentile) combined with the low Conversion Rate (P15) indicates visitors exit quickly without converting, supporting the poor performance assessment.\"\n"
        "- \"The metric relationship (high users P80+ + low conversion P15 + high bounce P85) creates a pattern where traffic volume doesn't translate to conversions, which directly supports the insight's conclusion.\"\n"
    ),
    "insight_deep_dive_recommendations": (
        "Follow-up request for one insight from a previous GA4 analysis.\n"
        "Insight:\n"
        "{USER_QUESTION}\n"
        "\n"
        "TASK:\n"
        "Provide a deeper, focused recommendation set for this exact insight. Each recommendation must be data-driven, metric-specific, and directly address the metric patterns identified in the insight.\n"
        "\n"
        "CRITICAL: NO SQL QUERIES ALLOWED\n"
        "- The insight text above already contains ALL the data you need: metric values, percentile positions, and metric relationships\n"
        "- DO NOT run any SQL queries or use the explore_table_data tool\n"
        "- Extract metric patterns and values directly from the insight text itself\n"
        "- The insight already includes specific values (e.g., \"1,200 users\", \"0.5%\", \"P80+\", \"P15\") - use these directly in your recommendations\n"
        "- Your job is to create recommendations based on the metric patterns ALREADY identified in the insight, not to query for new data\n"
        "- If you run SQL queries, you are wasting resources and providing recommendations that don't match the insight\n"
        "\n"
        "RECOMMENDATION REQUIREMENTS:\n"
        "Each recommendation must be:\n"
        "- Metric-Specific: Directly address the metric patterns identified in the insight (e.g., if insight mentions low Conversion Rate, recommendation must target conversion improvement with specific actions)\n"
        "- Data-Driven: Reference specific metric values, percentile positions, or thresholds from the insight (e.g., \"For pages with Conversion Rate < 1.5% and Bounce Rate > 70%, test reducing form fields\")\n"
        "- Actionable: Be a specific, measurable action tied to the observed data (e.g., \"A/B test checkout flow on pages with Conversion Rate below P20 and Sessions per User > 2.0\")\n"
        "- Directly Linked: Must directly correspond to the metric relationships identified in the insight\n"
        "- Focused: Address only the specific issue identified in the insight, not general optimization\n"
        "\n"
        "STRUCTURE REQUIREMENTS:\n"
        "Each recommendation should follow this pattern:\n"
        "\"For [specific condition based on insight metrics], [specific action] to [expected outcome tied to metric improvement]\"\n"
        "\n"
        "Examples:\n"
        "- \"For pages with Conversion Rate < 1.5% (P20-) and Bounce Rate > 70% (P80+), test reducing form fields from 5 to 3 to improve conversion by addressing friction points identified in the data.\"\n"
        "- \"On pages with high Total Users (P80+) but low Revenue per User (P20-), implement exit-intent popups with targeted offers to capture value from high-traffic, low-converting pages.\"\n"
        "- \"For pages showing high Session Length (P80+) but low Conversion Rate (P20-), add clear call-to-action buttons above the fold to convert engaged but non-converting visitors.\"\n"
        "\n"
        "OUTPUT RULES:\n"
        "- Be concise: 3-4 one-sentence recommendations maximum (aim for 20-35 words per recommendation)\n"
        "- Each recommendation must tie to one or more metric patterns from the insight\n"
        "- Reference specific metric values, percentile positions, or thresholds mentioned in the insight\n"
        "- Do not restate the full report or add unrelated sections\n"
        "- Do not provide generic advice that could apply to any page\n"
        "- Focus exclusively on the metric relationships and patterns identified in the insight\n"
        "- Avoid repetition - each recommendation should address a different aspect of the metric pattern\n"
        "\n"
        "FORMATTING:\n"
        "- Use plain text bullets starting with a hyphen and space (\"- \"), NOT markdown symbols like asterisks (*)\n"
        "- Do NOT use markdown formatting symbols (*, **, __, etc.) in your output\n"
        "- Output each recommendation on a new line starting with \"- \" (hyphen followed by space)\n"
        "- Example format: \"- For pages with Conversion Rate < 1.5% (P20-) and Bounce Rate > 70% (P80+), test reducing form fields...\"\n"
        "\n"
        "FORBIDDEN CONTENT:\n"
        "Do NOT include:\n"
        "- Generic UX/design advice without data support (e.g., \"improve page design\", \"make it more user-friendly\")\n"
        "- Recommendations that don't directly address the metric patterns shown in the insight\n"
        "- Vague statements like \"improve user experience\", \"optimize the page\", or \"enhance conversion\" without specific metric targets\n"
        "- Assumptions about user psychology or behavior not in the data\n"
        "- Recommendations that aren't tied to specific metric thresholds or patterns from the insight\n"
        "- General best practices that don't address the specific data pattern identified\n"
        "- Actions that can't be measured or tied back to the metrics in the insight\n"
        "\n"
        "ALIGNMENT WITH INSIGHT:\n"
        "- Extract the key metric patterns from the insight (e.g., high users + low conversion, high bounce + low session length)\n"
        "- Create recommendations that directly address each metric relationship identified\n"
        "- If the insight mentions specific pages or segments, tailor recommendations to those specific cases\n"
        "- Ensure each recommendation can be measured using the same metrics referenced in the insight\n"
    ),
}
